
import "./globals.css";
import StoreProvider from "../components/StoreProvider";



export const metadata = {
  title: "Aero2Astro Gis",
  description: "Generated by Rajnish Maurya",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider >
      
          {children} {/* Renders the active page */}
          
        </StoreProvider>
      </body>
    </html>
  );
}
