
import Navbar from "@/components/navbar";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Footer from "@/components/footer";

export const metadata = {
  title: "Aero2Astro Gis",
  description: "Generated by Rajnish Maurya",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider >
          <Navbar/>
          {children} {/* Renders the active page */}
          
        </StoreProvider>
      </body>
    </html>
  );
}
